# -*- coding: utf-8 -*-
"""interactive_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sIKWYNMUymwLFJbP03VjuOFRa4g69kv
"""

# ============================================================
# TASK 5 - INTERACTIVE DASHBOARD DEVELOPMENT
# VirtualWorks Lab Internship
# ============================================================

# Install required libraries (Run once)
!pip install streamlit plotly pandas

import streamlit as st
import pandas as pd
import plotly.express as px

# ------------------------------------------------------------
# Dashboard Title
# ------------------------------------------------------------

st.set_page_config(page_title="Business Performance Dashboard", layout="wide")

st.title("📊 Business Performance Dashboard")
st.write("Interactive dashboard showing sales performance and business insights.")

# ------------------------------------------------------------
# Sample Dataset
# ------------------------------------------------------------

data = {
    "Month": [
        "Jan", "Feb", "Mar", "Apr", "May", "Jun",
        "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
    ],
    "Sales": [12000, 15000, 18000, 17000, 21000, 24000,
              26000, 28000, 25000, 30000, 32000, 35000],
    "Profit": [3000, 3500, 4200, 3900, 5000, 6200,
               6800, 7200, 6900, 8100, 8500, 9300],
    "Customers": [120, 135, 150, 145, 165, 180,
                  195, 205, 198, 220, 235, 250]
}

df = pd.DataFrame(data)

# ------------------------------------------------------------
# Sidebar Filter
# ------------------------------------------------------------

selected_months = st.sidebar.multiselect(
    "Select Months",
    df["Month"],
    default=df["Month"]
)

filtered_df = df[df["Month"].isin(selected_months)]

# ------------------------------------------------------------
# KPI Metrics
# ------------------------------------------------------------

col1, col2, col3 = st.columns(3)

col1.metric("Total Sales", f"₹{filtered_df['Sales'].sum():,}")
col2.metric("Total Profit", f"₹{filtered_df['Profit'].sum():,}")
col3.metric("Total Customers", filtered_df["Customers"].sum())

# ------------------------------------------------------------
# Sales Trend
# ------------------------------------------------------------

fig_sales = px.line(
    filtered_df,
    x="Month",
    y="Sales",
    markers=True,
    title="Monthly Sales Trend"
)

st.plotly_chart(fig_sales, use_container_width=True)

# ------------------------------------------------------------
# Profit Trend
# ------------------------------------------------------------

fig_profit = px.bar(
    filtered_df,
    x="Month",
    y="Profit",
    title="Monthly Profit"
)

st.plotly_chart(fig_profit, use_container_width=True)

# ------------------------------------------------------------
# Customer Trend
# ------------------------------------------------------------

fig_customers = px.area(
    filtered_df,
    x="Month",
    y="Customers",
    title="Customer Growth"
)

st.plotly_chart(fig_customers, use_container_width=True)

# ------------------------------------------------------------
# Summary Table
# ------------------------------------------------------------

st.subheader("Business Data")

st.dataframe(filtered_df)

# ------------------------------------------------------------
# Key Insights
# ------------------------------------------------------------

st.subheader("Key Insights")

st.success("""
• Sales show consistent growth throughout the year.

• Profit increases alongside sales.

• Customer count grows steadily.

• Business performance is improving month by month.

• Continue focusing on customer acquisition and retention.
""")