# -*- coding: utf-8 -*-
"""Customer-Churn-Analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iUyuOnCCe2j43NQdnAfViK8xLfluXch4
"""

# ============================================================
# TASK 2 - CUSTOMER CHURN ANALYSIS
# VirtualWorks Lab Internship
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("=" * 60)
print("CUSTOMER CHURN ANALYSIS")
print("=" * 60)

# ------------------------------------------------------------
# STEP 1: Create Sample Customer Dataset
# ------------------------------------------------------------

data = {
    "Customer_ID": [101,102,103,104,105,106,107,108,109,110],
    "Age": [22,35,41,28,45,39,31,27,50,29],
    "Subscription_Months": [2,18,24,4,36,12,8,15,48,6],
    "Monthly_Usage_Hours": [5,35,42,8,50,20,12,28,55,10],
    "Support_Tickets": [4,1,0,5,0,2,3,1,0,4],
    "Payment_Method": [
        "Credit Card","UPI","Credit Card","Debit Card","UPI",
        "Credit Card","Debit Card","UPI","Credit Card","Debit Card"
    ],
    "Churn": [
        "Yes","No","No","Yes","No",
        "No","Yes","No","No","Yes"
    ]
}

df = pd.DataFrame(data)

print("\nOriginal Dataset\n")
print(df)

# ------------------------------------------------------------
# STEP 2: Dataset Information
# ------------------------------------------------------------

print("\nDataset Information\n")
print(df.info())

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

# ------------------------------------------------------------
# STEP 3: Data Cleaning
# ------------------------------------------------------------

# Remove duplicates
df = df.drop_duplicates()

# Fill missing values if any
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Monthly_Usage_Hours"] = df["Monthly_Usage_Hours"].fillna(df["Monthly_Usage_Hours"].mean())
df["Support_Tickets"] = df["Support_Tickets"].fillna(0)

# Standardize text
df["Payment_Method"] = df["Payment_Method"].str.title()
df["Churn"] = df["Churn"].str.title()

print("\nData Cleaning Completed Successfully.")

# ------------------------------------------------------------
# STEP 4: Overall Churn Rate
# ------------------------------------------------------------

print("\nOverall Churn Distribution\n")
print(df["Churn"].value_counts())

churn_rate = (df["Churn"] == "Yes").mean() * 100

print(f"\nOverall Churn Rate: {churn_rate:.2f}%")

# ------------------------------------------------------------
# STEP 5: Customer Behavior Analysis
# ------------------------------------------------------------

print("\nAverage Monthly Usage by Churn Status\n")
print(df.groupby("Churn")["Monthly_Usage_Hours"].mean())

print("\nAverage Subscription Duration\n")
print(df.groupby("Churn")["Subscription_Months"].mean())

print("\nAverage Support Tickets\n")
print(df.groupby("Churn")["Support_Tickets"].mean())

# ------------------------------------------------------------
# STEP 6: Visualizations
# ------------------------------------------------------------

# Churn Distribution
plt.figure(figsize=(6,4))
df["Churn"].value_counts().plot(kind="bar")
plt.title("Customer Churn Distribution")
plt.xlabel("Churn")
plt.ylabel("Number of Customers")
plt.tight_layout()
plt.show()

# Monthly Usage
plt.figure(figsize=(6,4))
df.groupby("Churn")["Monthly_Usage_Hours"].mean().plot(kind="bar")
plt.title("Average Monthly Usage")
plt.xlabel("Churn")
plt.ylabel("Hours")
plt.tight_layout()
plt.show()

# Subscription Duration
plt.figure(figsize=(6,4))
df.groupby("Churn")["Subscription_Months"].mean().plot(kind="bar")
plt.title("Average Subscription Duration")
plt.xlabel("Churn")
plt.ylabel("Months")
plt.tight_layout()
plt.show()

# Support Tickets
plt.figure(figsize=(6,4))
df.groupby("Churn")["Support_Tickets"].mean().plot(kind="bar")
plt.title("Average Support Tickets")
plt.xlabel("Churn")
plt.ylabel("Tickets")
plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# STEP 7: Key Insights
# ------------------------------------------------------------

print("\n" + "="*60)
print("KEY INSIGHTS")
print("="*60)

print("""
1. Customers with lower monthly usage are more likely to churn.

2. Customers with shorter subscription periods have a higher churn rate.

3. Customers raising more support tickets tend to cancel their subscriptions.

4. Long-term customers are generally more loyal.

5. Improving customer support and increasing user engagement may help reduce churn.
""")

# ------------------------------------------------------------
# STEP 8: Save Processed Dataset
# ------------------------------------------------------------

df.to_csv("customer_churn_analysis.csv", index=False)

print("Processed dataset saved as 'customer_churn_analysis.csv'")

print("\nTask Completed Successfully!")