# -*- coding: utf-8 -*-
"""web_traffic_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sIKWYNMUymwLFJbP03VjuOFRa4g69kv
"""

# ============================================================
# TASK 3 - WEB TRAFFIC ANALYTICS
# VirtualWorks Lab Internship
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("=" * 60)
print("WEB TRAFFIC ANALYTICS")
print("=" * 60)

# ------------------------------------------------------------
# STEP 1: Create Sample Website Traffic Dataset
# ------------------------------------------------------------

data = {
    "User_ID": [101,102,103,104,105,106,107,108,109,110],
    "Page_Visited": [
        "Home","Products","Home","About","Products",
        "Home","Contact","Products","Home","Checkout"
    ],
    "Page_Views": [5,8,3,2,10,7,1,9,6,4],
    "Session_Duration_Min": [12,20,8,5,25,18,3,22,15,10],
    "Bounce": ["No","No","Yes","Yes","No","No","Yes","No","No","Yes"],
    "Device": [
        "Mobile","Desktop","Mobile","Tablet","Desktop",
        "Mobile","Desktop","Tablet","Mobile","Desktop"
    ]
}

df = pd.DataFrame(data)

print("\nOriginal Dataset\n")
print(df)

# ------------------------------------------------------------
# STEP 2: Dataset Information
# ------------------------------------------------------------

print("\nDataset Information\n")
print(df.info())

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

# ------------------------------------------------------------
# STEP 3: Data Cleaning
# ------------------------------------------------------------

df = df.drop_duplicates()

df["Page_Visited"] = df["Page_Visited"].str.title()
df["Bounce"] = df["Bounce"].str.title()
df["Device"] = df["Device"].str.title()

print("\nData Cleaning Completed Successfully.")

# ------------------------------------------------------------
# STEP 4: Website Metrics
# ------------------------------------------------------------

total_page_views = df["Page_Views"].sum()

average_session = df["Session_Duration_Min"].mean()

bounce_rate = (df["Bounce"] == "Yes").mean() * 100

print("\n==============================")
print("KEY WEBSITE METRICS")
print("==============================")

print(f"Total Page Views : {total_page_views}")
print(f"Average Session Duration : {average_session:.2f} Minutes")
print(f"Bounce Rate : {bounce_rate:.2f}%")

# ------------------------------------------------------------
# STEP 5: User Journey Analysis
# ------------------------------------------------------------

print("\nMost Visited Pages\n")
print(df["Page_Visited"].value_counts())

print("\nAverage Session Duration by Device\n")
print(df.groupby("Device")["Session_Duration_Min"].mean())

print("\nBounce by Device\n")
print(df.groupby("Device")["Bounce"].value_counts())

# ------------------------------------------------------------
# STEP 6: Visualizations
# ------------------------------------------------------------

# Most Visited Pages
plt.figure(figsize=(6,4))
df["Page_Visited"].value_counts().plot(kind="bar")
plt.title("Most Visited Pages")
plt.xlabel("Pages")
plt.ylabel("Visits")
plt.tight_layout()
plt.show()

# Session Duration
plt.figure(figsize=(6,4))
df.groupby("Page_Visited")["Session_Duration_Min"].mean().plot(kind="bar")
plt.title("Average Session Duration by Page")
plt.xlabel("Page")
plt.ylabel("Minutes")
plt.tight_layout()
plt.show()

# Device Usage
plt.figure(figsize=(6,4))
df["Device"].value_counts().plot(kind="bar")
plt.title("Website Traffic by Device")
plt.xlabel("Device")
plt.ylabel("Users")
plt.tight_layout()
plt.show()

# Bounce Rate
plt.figure(figsize=(6,4))
df["Bounce"].value_counts().plot(kind="bar")
plt.title("Bounce Analysis")
plt.xlabel("Bounce")
plt.ylabel("Users")
plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# STEP 7: Drop-Off Analysis
# ------------------------------------------------------------

drop_off_pages = df[df["Bounce"]=="Yes"]["Page_Visited"].value_counts()

print("\nDrop-Off Pages\n")
print(drop_off_pages)

# ------------------------------------------------------------
# STEP 8: Insights
# ------------------------------------------------------------

print("\n" + "="*60)
print("INSIGHTS")
print("="*60)

print("""
1. Home and Products pages receive the highest number of visits.

2. Users spending more time on the website are less likely to leave immediately.

3. Bounce rate indicates pages where users exit quickly.

4. Mobile users contribute a significant portion of website traffic.

5. Improving page content and navigation can reduce drop-offs and increase engagement.
""")

# ------------------------------------------------------------
# STEP 9: Save Processed Dataset
# ------------------------------------------------------------

df.to_csv("web_traffic_analytics.csv", index=False)

print("\nProcessed dataset saved as 'web_traffic_analytics.csv'")

print("\nTask Completed Successfully!")