# -*- coding: utf-8 -*-
"""geospatial_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sIKWYNMUymwLFJbP03VjuOFRa4g69kv
"""

# ============================================================
# TASK 4 - GEOSPATIAL DATA ANALYSIS
# VirtualWorks Lab Internship
# ============================================================

# Install folium (Run only in Google Colab)
# !pip install folium

import pandas as pd
import folium

print("=" * 60)
print("GEOSPATIAL DATA ANALYSIS")
print("=" * 60)

# ------------------------------------------------------------
# STEP 1 : Create Sample Business Dataset
# ------------------------------------------------------------

data = {
    "City": [
        "Hyderabad",
        "Bangalore",
        "Chennai",
        "Mumbai",
        "Delhi",
        "Pune",
        "Kolkata",
        "Ahmedabad",
        "Jaipur",
        "Visakhapatnam"
    ],

    "Latitude":[
        17.3850,
        12.9716,
        13.0827,
        19.0760,
        28.7041,
        18.5204,
        22.5726,
        23.0225,
        26.9124,
        17.6868
    ],

    "Longitude":[
        78.4867,
        77.5946,
        80.2707,
        72.8777,
        77.1025,
        73.8567,
        88.3639,
        72.5714,
        75.7873,
        83.2185
    ],

    "Sales":[
        950,
        1200,
        780,
        1500,
        1400,
        850,
        600,
        500,
        700,
        1100
    ],

    "Business_Presence":[
        "High",
        "High",
        "Medium",
        "High",
        "High",
        "Medium",
        "Low",
        "Low",
        "Low",
        "Low"
    ]
}

df = pd.DataFrame(data)

print("\nOriginal Dataset\n")
print(df)

# ------------------------------------------------------------
# STEP 2 : Dataset Information
# ------------------------------------------------------------

print("\nDataset Information\n")
print(df.info())

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

# ------------------------------------------------------------
# STEP 3 : Data Cleaning
# ------------------------------------------------------------

df = df.drop_duplicates()

df["City"] = df["City"].str.title()
df["Business_Presence"] = df["Business_Presence"].str.title()

print("\nData Cleaning Completed Successfully.")

# ------------------------------------------------------------
# STEP 4 : Sales Analysis
# ------------------------------------------------------------

print("\nTop Cities by Sales\n")

top_sales = df.sort_values(by="Sales", ascending=False)

print(top_sales)

# ------------------------------------------------------------
# STEP 5 : Identify High Demand - Low Presence
# ------------------------------------------------------------

potential_locations = df[
    (df["Sales"] > 900) &
    (df["Business_Presence"] == "Low")
]

print("\nPotential Expansion Locations\n")

print(potential_locations)

# ------------------------------------------------------------
# STEP 6 : Create Interactive Map
# ------------------------------------------------------------

india_map = folium.Map(
    location=[21.0,78.0],
    zoom_start=5
)

for index,row in df.iterrows():

    if row["Business_Presence"]=="High":
        color="green"

    elif row["Business_Presence"]=="Medium":
        color="orange"

    else:
        color="red"

    folium.Marker(

        location=[row["Latitude"],row["Longitude"]],

        popup=f"""
        City: {row['City']}
        Sales: {row['Sales']}
        Presence: {row['Business_Presence']}
        """,

        icon=folium.Icon(color=color)

    ).add_to(india_map)

india_map.save("business_expansion_map.html")

print("\nInteractive Map Saved Successfully!")

# ------------------------------------------------------------
# STEP 7 : Insights
# ------------------------------------------------------------

print("\n" + "="*60)
print("BUSINESS INSIGHTS")
print("="*60)

print("""

1. Mumbai and Delhi have the highest sales.

2. Hyderabad and Visakhapatnam also show strong customer demand.

3. Cities with HIGH sales but LOW business presence
   are good candidates for expansion.

4. Expanding into these regions can improve market reach.

5. Interactive map highlights business presence across India.

""")

# ------------------------------------------------------------
# STEP 8 : Save Dataset
# ------------------------------------------------------------

df.to_csv("geospatial_business_analysis.csv", index=False)

print("\nDataset saved as 'geospatial_business_analysis.csv'")

print("\nTask Completed Successfully!")